management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: true
    diskspace:
      enabled: true


---
server:
  port: ${SERVER_PORT}
  url: http://${SERVER_HOST}
---
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: ${MYSQL_DDL_AUTO}
    show-sql: true
    defer-datasource-initialization: ${DATASOURCE_INIT}
  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  #    properties:
  #      hibernate:
  #        dialect: org.hibernate.dialect.MySQLDialect
  #    defer-datasource-initialization: true
  #    generate-ddl: true
  #    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      mode: ${INIT_MODE}
      continue-on-error: true
  security:
    oath2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

bistro:
  master:
    database:
      mysql:
        url: jdbc:mysql://${MYSQL_HOST:mysqldb_master}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:restaurant_management}
        username: ${MYSQL_USERNAME}
        password: ${MYSQL_PASSWORD}
        driverClassName: com.mysql.cj.jdbc.Driver
#  slave:
#    database:
#      mysql:
#        url: jdbc:mysql://mysqldb_slave:3306/restaurant_management_slave
#        username: bistrocheese
#        password: 12345678
#        driverClassName: com.mysql.cj.jdbc.Driver


---
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
      refresh-cookie-name: ${JWT_REFRESH_COOKIE_NAME}

MAIL_PASSWORD: uksl lulr xunq fvsk
