---
server:
  port: ${SERVER_PORT}
  url: http://${SERVER_HOST}
---
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: ${MYSQL_DDL_AUTO}
    show-sql: true
    defer-datasource-initialization: ${DATASOURCE_INIT}
  #    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
  #    defer-datasource-initialization: true
#    generate-ddl: true
  #    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:mysqldb}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:restaurant_management}
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      mode: ${INIT_MODE}
      continue-on-error: true
  security:
    oath2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

bistro:
  database:
    mysql:
      url: jdbc:mysql://${MYSQL_HOST:mysqldb}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:restaurant_management}
      username: ${MYSQL_USERNAME}
      password: ${MYSQL_PASSWORD}
      driverClassName: com.mysql.cj.jdbc.Driver

---
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      access-token:
        expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
      refresh-cookie-name: ${JWT_REFRESH_COOKIE_NAME}
