#Server
SERVER_HOST: bistrocheesespring
SERVER_PORT: 8080

#Database
MYSQL_HOST: mysqldb_master
MYSQL_PORT: 3306
MYSQL_DATABASE: restaurant_management_master
MYSQL_USERNAME: bistrocheese
MYSQL_PASSWORD: 12345678
MYSQL_DDL_AUTO: none

#Init Data
INIT_MODE: always
DATASOURCE_INIT: true

#JWT
JWT_SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
JWT_ACCESS_TOKEN_EXPIRATION: 18000000
JWT_REFRESH_TOKEN_EXPIRATION: 86400000
JWT_REFRESH_COOKIE_NAME: jwt-refresh-token

#OAuth2.0
GOOGLE_CLIENT_ID: 355251898698-c9lfdc0vo8ukd3ig7670nonra0tbj4p8.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 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

#Mail
MAIL_HOST: smtp.gmail.com
MAIL_PORT: 587
MAIL_USERNAME: winqti@gmail.com
